### model
model_name_or_path: /xpfs/public/models/hf_models/map-neo-7b

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: math_4_code_feedback
template: llama2
cutoff_len: 4096
max_samples: 10000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /gpfs/public/research/xy/yubowang/lkg_models_0831/output_models_MATH_cluster/math_4_code_feedback_const/map-neo-7b
logging_steps: 1
save_steps: 200
plot_loss: true
overwrite_output_dir: true
save_only_model: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 16
learning_rate: 2.0e-5
num_train_epochs: 12.0
lr_scheduler_type: constant_with_warmup
warmup_ratio: 0.01
fp16: true
ddp_timeout: 180000000

### eval
val_size: 0.0001
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 10000
