### model
model_name_or_path: /ML-A800/models/Qwen2-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: gsm8k_2_math_instruct
template: qwen
cutoff_len: 4096
max_samples: 10000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: output_models_math/gsm8k_test_2_cot/qwen2-7b-instruct
logging_steps: 1
save_steps: 400
plot_loss: true
overwrite_output_dir: true
save_only_model: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 16
learning_rate: 5.0e-6
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
fp16: true
ddp_timeout: 180000000

### eval
val_size: 0.001
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 10000
