### model
model_name_or_path: /xpfs/public/models/hf_models/mistral-7b

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: gsm8k_4_math_instruct
template: llama2
cutoff_len: 4096
max_samples: 10000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: output_models_MATH_cluster/gsm8k_test_4_cot/mistral-7b
logging_steps: 1
save_steps: 200
plot_loss: true
overwrite_output_dir: true
save_only_model: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 16
learning_rate: 2.0e-5
num_train_epochs: 6.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
fp16: true
ddp_timeout: 180000000

### eval
val_size: 0.0001
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 10000
